### ISSUE TITLE
Handle PyBind11 License

### ISSUE THREAD

**Issue by Teschl** [TopoToolbox/pytopotoolbox#20]
Since PyBind11 is using a BSD-style license that, among other things, states: 

"2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution."
[from pybind11 license](https://github.com/pybind/pybind11/blob/master/LICENSE)
   
Does that mean we also have to include the license in our repository? If so, we'll probably need to check all other dependencies for similar requirements.

**Comment by wkearn** [comment]
I think you are probably right: we need to provide the pybind11 license somewhere in the package that we ship to users. It seems like scipy does this with a separate LICENSES_bundled.txt that includes the license for all of their dependencies, which seems like a good enough solution for the moment. I'll submit a PR momentarily with that file.

I think pybind11 is the only one we need to worry about at the moment because we don't distribute source or binary artifacts of any of the other dependencies (matplotlib, rasterio, etc.). `pip` pulls those in for the user.
