### ISSUE TITLE
Implement FlowObject

### ISSUE THREAD

**Issue by wkearn** [TopoToolbox/pytopotoolbox#60]
With TopoToolbox/libtopotoolbox#72, we should have everything that we need to create a FlowObject from a GridObject.

The basic workflow, which corresponds to TopoToolbox v2 `FLOWobj(dem,'preprocess','carve')`, would, in C, look something like:

```C
fillsinks(filled_dem, dem, dims);

identifyflats(flats,filled_dem,dims);

gwdt_computecosts(costs, conncomps, flats, dem, filled_dem, dims);

gwdt(dist, prev, costs, flats, heap, back, dims);

flow_routing_d8_carve(source, direction, filled_dem, dist, flats, dims);

// Compute downstream target from source and direction
```

The results that we need to store in the `FlowObject` are the two arrays `source`, which is a topologically sorted list of source pixels in the flow network, and `target`, which is the corresponding downstream pixel for each source pixel.

At the moment `flow_routing_d8_carve` doesn't actually return the `target` array. Instead it fills in a `direction` array that encodes the flow direction at each pixel. I will add a libtopotoolbox function `flow_routing_targets_from_direction` or something like that to fill in a `targets` array from the sources and flow directions, and we can use that at the end.

**Comment by wkearn** [comment]
This is probably blocked by #53 because the newer libtopotoolbox functions only have the new dimensions interface.

**Comment by Teschl** [comment]
I'm working on #53 and #45 right now, so the FlowObject implementation can be added after that.

**Comment by Teschl** [comment]
There is a decision to make regarding the creation of a FlowObject. 

1. We create a function in utils which needs a GridObject as an argument:
Using this option, we could implement a version where DEM could also be the path to a TIF file, for example.
```python
DEM = topotoolbox.load_dem('perfectworld')
FLOW = topooolbox.gen_FlowObject(DEM)
```
2. Or we add a function to the class GridObject:
```python
DEM = topotoolbox.load_dem('perfectworld')
FLOW = DEM.gen_FlowObject()
```
3. Probably too convoluted but still possible:
```python
DEM = topotoolbox.load_dem('perfectworld')
FLOW = topotoolbox.FlowObject.new_object(DEM)
```
4. Something else entirely

I think option two is the way to go, but this could lead to confusion, since using this solution will result in a completely different creation process between FlowObject and GridObject for the user.

**Comment by wkearn** [comment]
Is is possible to pass the `GridObject` to the `FlowObject` constructor? Something like `FD = FlowObject(DEM)` This is more or less how MATLAB TT does it.

There are a few different ways to construct a `GridObject`. I think there should only be one way to construct a `FlowObject` because a `FlowObject` only makes sense when referenced to an underlying `GridObject`. 

We could create it directly from the file, as you suggested in option 1, but we still have to load the data from the file and do everything we already do for `GridObject`, so it doesn't really save us any work.

If making the `FlowObject` constructor take a `GridObject` doesn't really work, I think I prefer option 2, the method on `GridObject`, because it makes the dependency between the `FlowObject` and `GridObject` clear. We might call the method something different, like `GridObject.route_flow` to make it more clear what we are actually doing.

**Comment by Teschl** [comment]
Yeah, it's possible to implement it like this:
```python
DEM = topotoolbox.load_dem('perfectworld')
FD = topotoolbox.FlowObject(DEM)
```
Also, adding opinion two will be easy since it's just a wrapper for the constructor.

The way I'm implementing this right now is just calling the PyBind11 wrapper functions in the constructor of the GridObject without creating a GridObject function for each. For example, using `gwdt` as a python function that returns a new GridObject is unnecessary when using it in the constructor where only the np.ndarray is needed.

**Question regarding datatype and layout:**
Regarding the different variables used to create a FlowObject. It is hard to keep track of what variable should be which datatype and size. Below I have listed what I'm currently using:

```python
fillsinks(filled_dem, dem, dims)
# filled_dem: size/layout of dem and dtype=float (32?)

identifyflats(flats,filled_dem,dims)
# flats: size/layout of dem and dtype=int32

gwdt_computecosts(costs, conncomps, flats, dem, filled_dem, dims)
# costs: size/layout of dem and dtype=float (64?)
# conncomps: size/layout of dem and dtype=int64

gwdt(dist, prev, costs, flats, heap, back, dims)
# dist: size/layout of dem and dtype=float (32?)
# prev: size/layout of dem and dtype=int64
# heap: size/layout of dem and dtype=int64
# back: size/layout of dem and dtype=int64

flow_routing_d8_carve(source, direction, filled_dem, dist, flats, dims)
# source: size/layout of dem and dtype=int64
# direction: size/layout of dem and dtype=uint8

flow_routing_targets(target, source, direction, dims)
# target: what size/layout should this be? and dtype int64
```

Could you give some clarification on the dtypes and layout/size of the different variables @wkearn ? I want to make sure it's fine to just copy `dem` but filled with zeros when using the same size/layout. Should some variables be filled with something other than zero when calling the different functions?

**Comment by Teschl** [comment]
Ok, thanks for the clarification. 

> Is there a better way to present this information?

I think the only reason this was not immediately obvious to me was because it's just the pointer that is passed to each function. Knowing that every array has the same shape solves this issue. Maybe referencing that in the documentation, along with the expected contents of each array, will clear things up. Like in excesstopography for example: 

+ threshold_slopes – [in] The threshold slopes (tangent of the critical angle) at each grid cell. A float array of size (dims[0] x dims[1]).

> You could also reuse some intermediate arrays, such as the int64 arrays.

This seems like a great way to reduce memory usage, I'll look into that!
